nss-day-cohort-38/bangazon-ecommerce-web-app-iris-station

src/components/cards/HomeListCard.js
src/components/cards/homecss.css
src/components/cards/index.js
src/modules/productManager.js
src/pages/Router.js
src/pages/home/HomePage.css
src/pages/home/HomePage.js
src/pages/home/index.js

Fixes #18 
```shell
git checkout kk-new-home-list
python manage.py runserver
```
#FOR THE WEB APP
```shell
git checkout kk-homelist
npm start
```
added the functionality to only pull the most recent 20 products
added a new card to show products on the homepage
- added some sweet cards ♥️ 
- they show the product and the description and the date created (not formated yet)
- the card may change to have a details button instead of the drop down description. 
- once both servers are running just visit the homepage and see that it shows up. only the 3 current products we have are being listed cause we dont have more than 20.

finished adding home cards to list

---

.gitignore
src/components/cards/HomeListCard.js
src/components/cards/homecss.css
src/modules/productManager.js
src/pages/Router.js
src/pages/home/HomePage.js
src/pages/products/index.js
src/pages/products/productDetails.css
src/pages/products/productDetails.js

Fixes # 13 a (not associated yet)
```shell
git checkout kk-product-details-react
```
```shell
git checkout kk-product-details
```
added the ability to view product details once you click "See More" you will be directed to a webpage showing the details. I also added functionality to change the look of different cards to break up the 'wall of cards' look, it wont show up until more products are in there. I may decrease the amount of times it happens later. 
- added details page to react and then added conditional to HomeCardList.js to alter the card it returns (added route change as well and fixed minor p-tag bug)
- added to the retrieve method in Django to fetch one specific product
-Add to …

Kk product details react

---

src/pages/Router.js
src/pages/products/ProductForm.js

Fixes # 1
```shell
git checkout ag-sell-product
```
Check that"Sell Product" does not appear in the nav unless you are logged in.
Check that all fields must be completed in order to submit the form - a warning will be given if any field is not completed.
Check that you are redirected to the product detail view for that product upon submission
- Back End:
producttypes api built
- Front End:
sell product form built

Ag sell product

---

src/components/cards/cartcard.js
src/components/cards/index.js
src/modules/order_product_manager.js
src/pages/Router.js
src/pages/orders/index.js
src/pages/orders/mycart.js

Fixes #55 
```shell
git checkout kk-my-cart
```
This is a new navbar page that allows the user to view their current cart. When the user clicks the cart icon they will be directed to a page that shows the items in their cart. Note: none of the buttons work yet (remove or add another that is a different issue ticket)
- I added a new serializer to the order-product page and it is permanently expanding the product.
- Added a new item to the navbar (shopping cart icon)
- added a my cart page to get added to the DOM when activated

view order is functioning

---

src/components/cards/cartcard.js
src/modules/order_product_manager.js
src/pages/orders/mycart.js

Fixes #6 
```shell
git checkout kk-delete-orderproduct
```
I just added the ability to delete a product in order
- added destroy function to backend orderproduct viewset
- added a fucntion on the react side in mycart to delete that specific product from order

added delete to order product

---

src/components/expansion/Expansion.js
src/components/expansion/index.js
src/components/index.js
src/components/menu/VerticalMenu.js
src/components/navbar/Navbar.js
src/components/paper/Paper.js
src/modules/index.js
src/modules/orderDataManager.js
src/modules/orderManager.js
src/modules/order_product_manager.js
src/pages/Router.js
src/pages/customers/Profile.js
src/pages/customers/ProfilePages/OrderHistory.js
src/pages/customers/ProfilePages/index.js
src/pages/customers/index.js
src/pages/products/productDetails.js
src/styles/Global.css
src/styles/OrderHistory.css
src/styles/PaperComponent.css

Fixes #16 
```shell
git checkout tct-order-history
```
If a user is logged in and they go to their profile, then to order history, their order history should show up. The details of each order can be vied when the details link is clicked.
- Created an Expansion Component [code](https://github.com/nss-day-cohort-38/bangazon-ecommerce-web-app-iris-station/compare/tct-order-history#diff-50b039e33c849f5ec51334dbb7e632a3)
- Updated Vertical Menu to have active tab on refresh [code](https://github.com/nss-day-cohort-38/bangazon-ecommerce-web-app-iris-station/compare/tct-order-history#diff-03afa2bb8e77d8c5e8099d5429a1ff7fR5)
- Added key to vertical menu to get rid of error [code](https://github.com/nss-day-cohort-38/bangazon-ecommerce-web-app-iris-station/compare/tct-order-history …

Tct order history

---

src/components/cards/HomeListCard.js
src/modules/kk-paymenttypes.js
src/modules/orderManager.js
src/modules/productManager.js
src/pages/Router.js
src/pages/home/HomePage.js
src/pages/orders/checkout.js
src/pages/orders/depleteProduct.js
src/pages/orders/index.js
src/pages/orders/mycart.js
src/pages/products/productDetails.js

Fixes #2 
```shell
git checkout kk-checkout
```
I finished the checkout functionality. I had to add a whole lot so get ready. A user would like to checkout out so from their cart they click checkout and go to a small form which allows them to choose a payment method from there they will hit submit and be directed to the home page. things to notice the quantity of each object will be depleted by one.
bug: doesn't account for in stock is 0 (TBD stretch)
- list method for payment types (user specific)
- alter order list to show customer details as well 
- added Update method on order 
-added update method on products (to change quantity)
- FRONT END
- added new route for checkout 
- added function that depletes …

Kk checkout

---

src/components/cards/MyListCard.js
src/components/cards/cartcard.js
src/modules/productManager.js
src/pages/Router.js
src/pages/products/MyProducts.js
src/pages/products/ProductForm.js

Fixes #19 
```shell
git checkout ag-my-product
```
**Front End**
- Added files "MyProducts" and "MyListCard" and added My Products to the nav
**Back End**
- Added Destroy method to products.py
- Edited the List method to filter products by user for the "my products" page

Ag my products

---

src/components/buttons/Button.js
src/modules/paymentDataManager.js
src/pages/customers/Profile.js
src/pages/customers/ProfilePages/OrderHistory.js
src/pages/customers/ProfilePages/Payments.js
src/pages/customers/ProfilePages/index.js
src/pages/customers/index.js

Fixes #8 
```shell
git checkout tct-delete-paymenttype
```
User can now delete payment type
- 
-

Tct delete paymenttype

---

src/components/cards/HomeListCard.js
src/components/cards/MyListCard.js
src/components/cards/cartcard.js
src/components/cards/homecss.css
src/components/form/login.js
src/components/form/payment.js
src/components/form/register.js
src/components/navbar/Navbar.js
src/modules/api/userManager.js
src/pages/Router.js
src/pages/customers/ProfilePages/OrderDetail.js
src/pages/customers/ProfilePages/OrderHistory.js
src/pages/customers/ProfilePages/Payments.js
src/pages/customers/ProfilePages/index.js
src/pages/design-library/Home.js
src/pages/design-library/Pages/NavbarView.js
src/pages/home/HomePage.css
src/pages/home/HomePage.js
src/pages/products/ProductForm.js
src/pages/products/productDetails.css
src/pages/products/productDetails.js
src/styles/Global.css
src/styles/Navbar.css
src/styles/OrderHistory.css

```shell
git checkout tct-styling
```
Added styling to the application
- Home Screen Feature Card
- Got rid of three dots on home card
- Got rid of ad another button on cart card
- Added styling to sell product form
- Updated Navbar
- Updated link to login page and register page
- Added functionality to get userInfo

Tct styling

---

public/index.html
src/components/cards/cartcard.js
src/pages/orders/checkout.css
src/pages/orders/checkout.js
src/pages/orders/mycart.css
src/pages/orders/mycart.js
src/pages/products/productDetails.css
src/pages/products/productDetails.js

Fixes # NA
```shell
git checkout kk-stylesss
```
front end
```
git checkout kk-stylessss
```
fixed the issue when you delete a product thats you created it will then delete the product in someones cart (the relationship) test past ones for me.
updated styling for checkout out
- 
- 
- [] I have commented my code, particularly in hard-to-understand areas

Kk stylessss

---

PULL_REQUEST_TEMPLATE.md
src/components/form/payment.js
src/pages/customers/ProfilePages/AddPayment.js

Fixes #25 
```shell
git checkout tct-expiration-date
```
User cannot select a month/year in the future.
- Updated pull request template with test checkmark
- Added custom validation on payment form
- Changed size of fields on payment form
- Changed date field to two different drop downs for expiration date
- Payment form clears on submit
- Empty field cannot be submitted
- You cannot select month/year from the past including the current month.
- If no month is selected year selector is disabled
- Payment clears on submit
- Payment submit message disappears after user tries to add another one
- Old errors disappear on submit
- Select 6/2020, then try to select an earlier month in 2020 and make sure the year updates to 2021

Tct expiration date

---

src/pages/products/ProductForm.js
src/pages/products/testCharacters.js

Fixes #30 #3 
```shell
git checkout kk-sell-product-edits
```
I know only 1 ticket per pull request but they were so short I don't want to waste time. I added a function to test whether a product's title has !@#$%^&*( or ) in it. Then i just made the location field optional
- added a helper function to the products pages directory
- removed required from the input for location and changed the placeholds
- integrated the helper function into validation for the form
- check that you can check the availb for local
- this will alter what is placed in the database
- check available
- enter something in
- uncheck available and the location should be null still

Kk sell product edits

---

src/components/cards/HomeListCard.js
src/components/form/index.js
src/components/form/searchForm.js
src/components/navbar/Navbar.js
src/modules/productManager.js
src/pages/Router.js
src/pages/products/productDetails.js

Fixes #4 #5 
```shell
git checkout ag-search-products
```
you can search products
the search should only return products based on their title, description and location - not price quantity price image_path created_at or any of the ids
- added a search results page "searchForm"
- added "searchField" to state in Router.js
- added the appropriate things to the navbar

Ag search products

---

src/components/cards/HomeListCard.js
src/components/cards/MyListCard.js
src/components/cards/cartcard.js
src/pages/customers/ProfilePages/OrderDetail.js
src/pages/products/ProductForm.js
src/pages/products/productDetails.js

Fixes #14 #26
```shell
git checkout kp-image-upload
git pull
```
Pillow had to be installed for picture handling reasons...
```
pip install -r requirements.txt
```
Models have been changed to allow images to be uploaded (as opposed to just being url paths), so you'll have to migrate those:
```
python manage.py makemigrations
python manage.py migrate
```
Product Fixtures have been updated to utilize new images in the media folder, so install them:
```
python manage.py loaddata */fixtures/product.json
```
```shell
git checkout kp-image-upload
git pull
```
- Users can upload images when creating new products
- Those images are stored in the /media/` folder on the back end api repo (note: they are …

Kp image upload

---

README.md

Fixes # NA
```shell
git checkout kk-readme
```
made a read me. it is just draft one so if you see anything I should add let me know!
- read me
-

whoops, read me draft 1

---

src/components/alerts/CartSnackbar.js
src/components/alerts/index.js
src/components/cards/HomeListCard.js
src/components/cards/cartcard.js
src/components/form/searchForm.js
src/components/index.js
src/components/navbar/Navbar.js
src/pages/Router.js
src/pages/home/HomePage.js
src/pages/products/productDetails.js
src/styles/Navbar.css

Fixes #61 
```shell
git checkout tct-cart-message-style
```
Updated styling for navbar search bar, right side links in navbar, and add to cart messages.
- Added CartSnackBar component
- Added Updated Snackbar to HomeListCard
- Added Margin to Navabr Profile, Logout, and search bar items
- Made search bar button smaller
- Added Cart message when user adds anything to cart.
#test 
- Search still works
- Check that when any thing is added to a cart (Home page, search, and details view), that a message shows
- Check message for when user is logged out (Home page, search, and details view) and tries to add item to a cart
- Check that search bar shows up if user is logged in, and when they aren't logged in.
-

Tct cart message style

---

src/pages/orders/mycart.js
src/pages/products/ProductForm.js
src/pages/products/productDetails.js

Fixes # NA
```shell
git checkout kk-cancel-0-items
```
I fixed a bug where if the user adds items to the cart and then deletes them it still shows a cart. Now, one the deletion of the last item in the cart the whole order will get deleted. Fixed the details page so that it shows location or not availble for local pickup. NOTE: some database structures may have previously been recorded as "" or empty but need to be null (the program records empty strings as null for that input)
- product details
- order page

Kk cancel 0 items

---

src/components/cards/HomeListCard.js
src/components/cards/MyListCard.js
src/pages/customers/ProfilePages/Payments.js
src/pages/products/productDetails.js

```shell
git checkout ag-remove-time-from-date
```
removed the time from the date listed on the home page, product details, my products page, and payment types in the profile
- added .split("T")[0] to the appropriate files.
- added an if statement to the details file to check if it is undefined, as it causes an error if it is

removed time from date

---

src/components/expansion/Expansion.js
src/components/expansion/expansion.css
src/pages/customers/ProfilePages/Payments.js
src/styles/OrderHistory.css

Fixes #64 
```shell
git checkout tct-payment-list-style
```
The Payment Type list in profile's style has changed. Pretty much ripped off Amazon's
- Changed Payment Cards to Expansions

finished styling

---

src/components/index.js
src/components/menu/Drawer.js
src/components/menu/index.js
src/pages/design-library/Home.js
src/pages/design-library/Pages/MenuView.js

```shell
git checkout tct-drawr
```
Added a drawer component
- Added a Drawer component to Menu
- Added DL Drawer description
go to http://localhost:3000/dl/menus to see an example and explanation of the component

Tct drawer

---

src/components/navbar/Navbar.js

Fix for Home Page and NavBar
```shell
git checkout mc-fix-drawer-rerender
```
After user logs in or signs up, the drawer should be poplulated with the data. Fixed issue of hving to refresh the page in order for it to re render. 
-Log in
- Dont refresh, click the product categories button and make sure the data is there.

fix: home page and nav bar re render
